```{r}
library(tidyverse)
library(gender)
library(lubridate)
library(janitor)
library (ggthemr)
library(ggedit)


#load data
nyc_raw <- read_csv(file = 'dataset/citywide_payroll_data.csv')

nyc_data <- nyc_raw %>%
clean_names()

  
#Create Features

nyc_data <- nyc_data %>%
mutate(total_pay = regular_gross_paid + total_ot_paid + total_other_pay) %>%
mutate(total_hours = regular_hours + ot_hours) %>%
mutate(birth_year1 = '1960') %>%
mutate(birth_year2 = '1996')

# Create gender column and service years column.

results <- gender_df(nyc_data, name_col = "first_name", year_col = c("birth_year1", "birth_year2"),
                     method = 'ssa')
nyc_data <- nyc_data %>%
  left_join(results, by = c("first_name" = "name"))

end_2018 <- mdy(06302018)  # - Creating 'service_years' variable for seniority measurement.
nyc_data <- nyc_data %>%
  mutate(service_years = interval(end_2018, mdy(`agency_start_date`))) %>%
  mutate(service_years = as.numeric(as.period(service_years, unit = "year")) * -3.1689E-8) %>%
  mutate(service_years = round(service_years, digits = 0))

# Drop unneeded columns

nyc_data <- nyc_data %>%
select(-c(payroll_number, birth_year1, birth_year2, proportion_male, proportion_female, year_min, year_max))

# Create Pantaleo

nypd_pantaleo <- nypd_data %>%
filter(first_name == 'DANIEL' & last_name == 'PANTALEO')


```
```{r}



### NYPD EDA

nypd_data <- nyc_data %>%
  filter(agency_name == 'POLICE DEPARTMENT') %>%
  filter(total_pay > 0) %>%
  filter(service_years > 0) %>%
  mutate(work_location_borough = recode(work_location_borough, "RICHMOND" = 'STATEN ISLAND')) %>%
  mutate(agency_start_date = mdy(agency_start_date))
  
nypd_data %>%
ggplot(aes(gender))+ ## Employees by Year (Gender)
  geom_bar(na.rm = TRUE)+
  geom_text(stat='count', aes(label=..count..), vjust=-.25)+
  facet_grid(~fiscal_year)

```




```{r}

nypd_data %>%
  group_by(work_location_borough, gender) %>%  ## Gender % by borough
  summarise(N = n()) %>%
  mutate(freq = N/sum(N),
         pct = round(freq*100), 0) %>%
  ggplot(., aes(x = gender, y = pct))+
  geom_col()+
  facet_wrap(~work_location_borough)


```


```{r} 
#  Male/Female Median Pay by Median Service Years



nypd_data %>%
  group_by(gender, fiscal_year) %>%
  summarise(N = n(), median_pay = median(total_pay),
            median_service = median(service_years)) %>%
  mutate(freq = N / sum(N), 
         pct = round(freq*100), 0) %>%
  ggplot(., aes(fiscal_year, median_pay, color = gender))+
  geom_line()+
  geom_line(data = nypd_pantaleo,aes(x=fiscal_year, y=total_pay, color = last_name))




```



```{r} 

nypd_data %>%  ##  Top 10 job titles by gender
  filter(fiscal_year == 2018) %>%
  filter(agency_start_date < '2017-10-01') %>%
  filter(!is.na(gender)) %>%
  filter(gender == 'male') %>%
  group_by(gender, title_description) %>%
  summarise(N = n(), 
            median_pay = median(total_pay),
            median_ot = median(total_ot_paid)) %>%
  mutate(freq = N / sum(N),
         pct = round(freq*100), 0) %>%
  top_n(10, N) %>%
  arrange(desc(median_pay)) %>%
  ggplot(aes(x = reorder(title_description, -median_pay), y = median_pay))+
  geom_col()+
  coord_flip()

```

```{r}

nypd_data %>%  ##  Top 10 job titles by gender
  filter(fiscal_year == 2018) %>%
  filter(agency_start_date < '2017-10-01') %>%
  filter(!is.na(gender)) %>%
  filter(gender == 'female') %>%
  group_by(gender, title_description) %>%
  summarise(N = n(), 
            median_pay = median(total_pay),
            median_ot = median(total_ot_paid)) %>%
  mutate(freq = N / sum(N),
         pct = round(freq*100), 0) %>%
  top_n(10, N) %>%
  arrange(desc(median_pay)) %>%
  ggplot(aes(x = reorder(title_description, -median_pay), y = median_pay))+
  geom_col()+
  coord_flip()


```




